name: test-validate-domain

on:
  pull_request:

jobs:
  validate:
    name: Validate composite action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test validate domain action
        uses: ./actions/validate-domain
        with:
          chart-file: test/helm/Chart.yaml
