name: test-validate-domain

on:
  pull_request:
    paths:
    - "actions/validate-domain/**"
  
jobs:
  validate-domain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Test validate domain action
        uses: ./actions/validate-domain
        with:
          chart-file: test/helm/Chart.yaml
