name: Test update-charts-pr action

on:
  workflow_call:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v5

      - name: Run update-charts-pr action
        uses: ./actions/update-charts-pr
        with:
          tag: 0.0.0
          github_token: ${{ secrets.GH_PAT }}
          service_repo: test-service-repo
          update_paths: |
            infra/environments/dev.yaml
            infra/environments/prod.yaml
