name: Test auto-merge action

on:
  pull_request:
    paths:
      - "actions/auto-merge/**"

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v5

      - name: Run auto-merge action
        uses: ./actions/auto-merge
        with:
          pr_number: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.GH_PAT }}
          repository: ${{ github.repository }}
