name: Test update-charts-pr action

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Chart tag (version) to set"
        required: true
        type: string
      domain:
        description: "Domain folder in site-values (e.g. raster, vector, app)"
        required: true
        type: string

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v5

      - name: Run update-charts-pr action
        uses: ./actions/update-charts-pr
        with:
          tag: 0.0.0
          domain: infra
          github_token: ${{ secrets.GH_PAT }}
          service_repo: test-service-repo
