name: Test update-charts-pr action

on:
  workflow_call:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v5

      - name: Run auto-merge action
        uses: ./actions/auto-merge
        with:
          pr_number: 1
          github_token: ${{ secrets.GH_PAT }}
